`ApJdataFrames` 003: Luhman2004c
---
`Title`: New Brown Dwarfs and an Updated Initial Mass Function in Taurus  
`Authors`: Luhman K.L.

Data is from this paper:
http://iopscience.iop.org/0004-637X/617/2/1216/

In [1]:
import warnings
warnings.filterwarnings("ignore")

## Table 3- New Members of Taurus

In [2]:
import pandas as pd

In [3]:
names = ["Name_2MASS", "RA", "Dec", "Spectral Type", "Membership",
         "Teff", "AJ", "Lbol", "I", "I-zp","J-H","H-Ks", "Ks", "inIMF", "Night"]
tbl3 = pd.read_csv("http://iopscience.iop.org/0004-637X/617/2/1216/fulltext/60509.tb3.txt", sep='\t', names=names)
tbl3

,Name_2MASS,RA,Dec,Spectral Type,Membership,Teff,AJ,Lbol,I,I-zp,J-H,H-Ks,Ks,inIMF,Night
0,J04141188+2811535,04 14 11.88,28 11 53.5,M6.25\pm 0.5,"A_{V}, NaK, e",2962,0.28,0.0150,\ldots,\ldots,0.83,0.69,11.64,Yes,2
1,J04161210+2756385,04 16 12.10,27 56 38.6,M4.75,"A_{V}, NaK",3161,0.56,0.0540,\ldots,\ldots,1.16,0.78,10.34,Yes,2
2,J04163048+3037053,04 16 30.49,30 37 05.3,M4.5,NaK,3198,0.21,0.0110,\ldots,\ldots,0.65,0.35,12.62,No,4
3,J04202555+2700355,04 20 25.55,27 00 35.5,M5.25,"A_{V}, NaK, e",3091,0.56,0.0290,\ldots,\ldots,0.86,0.50,11.51,No,2
4,J04213459+2701388,04 21 34.60,27 01 38.9,M5.5,"A_{V}, NaK",3058,0.49,0.0650,\ldots,\ldots,0.93,0.53,10.44,No,2
5,J04284263+2714039,04 28 42.63,27 14 03.9,M5.25,NaK,3091,0.14,0.0400,\ldots,\ldots,1.04,0.61,10.46,No,2
6,J04380083+2558572,04 38 00.84,25 58 57.2,M7.25,NaK,2838,0.17,0.0600,14.71,1.27,0.92,0.53,10.10,Yes,1
7,J04381486+2611399,04 38 14.86,26 11 39.9,M7.25,"NaK, e",2838,0.00,0.0018,17.84,1.09,1.05,1.15,12.98,Yes,1
8,J04390396+2544264,04 39 03.96,25 44 26.4,M7.25,"NaK, e",2838,0.07,0.0200,15.63,1.22,0.81,0.47,11.37,Yes,1
9,J04403979+2519061,04 40 39.79,25 19 06.1,M5.25,"A_{V}, NaK",3091,0.70,0.0870,14.80,1.05,1.03,0.55,10.24,Yes,1
10,J04411078+2555116,04 41 10.79,25 55 11.7,M5.5,"A_{V}, NaK, e",3058,0.70,0.0240,16.24,0.99,1.07,0.67,11.45,Yes,1
11,J04414825+2534304,04 41 48.25,25 34 30.5,M7.75,"NaK, e",2752,0.28,0.0092,17.03,1.24,0.93,0.58,12.22,Yes,1
12,J04442713+2512164,04 44 27.13,25 12 16.4,M7.25,"NaK, e",2838,0.00,0.0280,\ldots,\ldots,0.84,0.60,10.76,No,2
13,J04552333+3027366,04 55 23.33,30 27 36.6,M6.25,NaK,2962,0.00,0.0130,15.55,1.02,0.68,0.42,11.97,Yes,2
14,J04554046+3039057,04 55 40.46,30 39 05.7,M5.25,NaK,3091,0.07,0.0210,14.71,0.76,0.64,0.30,11.77,Yes,1
15,J04554535+3019389,04 55 45.35,30 19 38.9,M4.75,NaK,3161,0.00,0.0680,13.19,0.65,0.65,0.33,10.46,Yes,1
16,J04554757+3028077,04 55 47.57,30 28 07.7,M4.75,NaK,3161,0.00,0.0980,13.01,0.75,0.74,0.33,9.98,Yes,3
17,J04554801+3028050,04 55 48.01,30 28 05.0,M5.6,NaK,3044,0.00,0.0120,15.20,0.87,0.59,0.43,12.15,Yes,3
18,J04554969+3019400,04 55 49.70,30 19 40.0,M6,NaK,2990,0.00,0.0160,15.02,0.88,0.58,0.37,11.86,Yes,1
19,J04555288+3006523,04 55 52.89,30 06 52.3,M5.25,NaK,3091,0.00,0.0540,13.70,0.74,0.61,0.30,10.73,Yes,1
20,J04555636+3049374,04 55 56.37,30 49 37.5,M5,NaK,3125,0.10,0.0440,13.85,0.69,0.61,0.30,11.09,Yes,1
21,J04574903+3015195,04 57 49.03,30 15 19.5,M9.25,NaK,2350,0.00,0.0011,19.25,1.40,0.65,0.64,14.48,Yes,1

# Save the data tables locally.

    !mkdir ../data/Luhman2004c

In [5]:
tbl3.to_csv("../data/Luhman2004c/tbl3.csv", sep="\t")

**The end.**